### ISSUE TITLE
Installing requirements_ipu.txt fails with duplicate jax dependency

### ISSUE THREAD

**Issue by ajwilkinson** [graphcore-research/pyscf-ipu#14]
This with pip 20.0.2 - error message of
```
ERROR: Double requirement given: jax==0.3.16+ipu (from -r requirements_ipu.txt (line 5)) (already in jax==0.3.16 (from -r requirements.txt (line 21)), name='jax')
```

**Comment by hatemhelal** [comment]
Thanks for reporting this, taking a look at a better fix.

**Comment by hatemhelal** [comment]
Hmm it does seem that the pip version makes a big difference. The environment I use has pip @ 23.2.1 which seems to be the most recently available and correctly interprets the intentionally duplicated requirements for jax.  Noting that pip version 20.0.2 was released over three years ago I am going to suggest that running `pip install --upgrade pip` would be a reasonable prerequisite.

@ajwilkinson, does that sound reasonable to you?

**Comment by ajwilkinson** [comment]
Yep upgrading pip makes this go away... perhaps put that in the readme? Thx! (And closing....)
