### ISSUE TITLE
Make molecule construction less stringy

### ISSUE THREAD

**Issue by awf** [graphcore-research/pyscf-ipu#19]
In a few places, we construct molecules using string concatenation; this is ugly and error-prone.
Let's replace with "list-of-atom" construction, i.e. replace
```
   "C 0 0 0; C 0 0 1"
```
with
```
   [("C", [0 0 0]),
    ("C", [0 0 1])]
```

https://github.com/graphcore-research/pyscf-ipu/blob/f2255e44b94314f6999fd9d19bfbbccd9a0db418/nanoDFT/symmetric_ERI.py#L11 

```py
 mol = pyscf.gto.Mole([("C", [0, 0, i]) for i in range(8)]), basis="sto3g")
```

**Comment by blazejba** [comment]
Fixed here: https://github.com/graphcore-research/pyscf-ipu/commit/e5582bef3fee5c3e057a8f1b8a324328fd114f09

**Comment by blazejba** [comment]
two more files covered here: https://github.com/graphcore-research/pyscf-ipu/pull/28
