### ISSUE TITLE
Fix `is_in_prev`  in `sparse_symmetric_ERI.py`

### ISSUE THREAD

**Issue by AlexanderMath** [graphcore-research/pyscf-ipu#33]
The electron repulsion integrals are stored in a tensor called `ERI`. The tensor satisfies an [8x symmetry](https://github.com/graphcore-research/pyscf-ipu/blob/main/nanoDFT/symmetric_ERI.py) and is [mostly zero (very sparse)](https://github.com/graphcore-research/pyscf-ipu/blob/main/nanoDFT/sparse_ERI.py). 

Both sparsity and 8x symmetry allows us to achieve memory savings. Using both tricks at the same time previously appeared tricky. The code in [sparse_symmetry_ERI.py](https://github.com/graphcore-research/pyscf-ipu/blob/main/nanoDFT/sparse_symmetric_ERI.py) uses both tricks at the same time all written in Jax. The code has passed several test cases, and brief profiling indicates the matrix multiplication timing is sufficiently fast. 

**Problem:** 
The check [is_in_prev](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/sparse_symmetric_ERI.py#L46) increases compile time from 1min to 20min for N=80. 

**Acceptable solutions:** 
Any code that computes the same as is_in_prev in a different way may solve the problem. I've tried four different algorithms without success. Worst case, we can write a custom poplar program for [compute_indices(..)](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/sparse_symmetric_ERI.py#L59C28-L59C28).

**Context (what does is_in_prev do?):**
The indices of [nonzero_distinct_ERI](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/sparse_symmetric_ERI.py#L19C22-L19C22) are used 1, 2, 4 or 8 times in the einsum computation. Example: ERI[0,0,0,0] is used once, ERI[1,1,2,2] is used twice, ERI[1,1,2,3] is use four times and ER[1,2,3,4] is used 8 times. The current code disregards this symmetry, i.e., it would multiply with ERI[0,0,0,0] eight times. This is currently fixed by the ["is_in_prev" check](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/sparse_symmetric_ERI.py#L46) which looks if (e.g.) ERI[0,0,0,0] was already used, and if so, it makes sure it's not used again (by returning -1 index which points to 0; a bit silly). The only problem is the code which computes whether i,j,k,l was already used, in particular, only the operation `matrix[:symmetry] == v]` on [this line](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/sparse_symmetric_ERI.py#L46). It seems any code which compares matrix with anything (itself, v, another copy of matrix, ...) breaks (this also indicates the slicing [:symmetry]) isn't the problem.

**Comment by balancap** [comment]
One idea to look at : let's exclude `ERI[0,0,0,0]`, `ERI[1,1,2,2]` and `ERI[1,1,2,3] ` from the general case, and write a specific code for each of these (i.e. all (sub-)diagonals). Hopefully, this would simplify the general case code, and avoid long compilation time?

**Comment by AlexanderMath** [comment]
other todo: add popvision profile
