### ISSUE TITLE
Number of integrals overflows in int32. 

### ISSUE THREAD

**Issue by AlexanderMath** [graphcore-research/pyscf-ipu#52]
For the 100 Carbons arranged in 10x10 2d grid the number of integrals is ~ 7B (computed [this line](https://github.com/graphcore-research/pyscf-ipu/blob/4aac401fc0cefdcff58f3c47a97a2a610737cefd/nanoDFT/sparse_symmetric_ERI.py#L151C35-L151C35)). We only keep the nonzero ones by using `nonzero_indices = np.nonzero(mol.intor("int2e_sph", aosym="s8"))` see [this line](https://github.com/graphcore-research/pyscf-ipu/blob/4aac401fc0cefdcff58f3c47a97a2a610737cefd/nanoDFT/sparse_symmetric_ERI.py#L165). 

That list of indices may then contain a number which is 7B big, larger than the biggest we can represent with even uint32 (2**32~ 4B << 7B). This means that, when we later cast the indices to int32 some of them will overflow. Because we use int32 (and not uint32) this may overflow to a negative number and subsequently cause [np.take](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.take.html) (and [segment_sum](https://jax.readthedocs.io/en/latest/_autosummary/jax.ops.segment_sum.html)) to use it's FILL_MODE which by default is NaN. 

**Experiment to test:** change indices from np.int32 to np.uint32; if this removes NaN this may be reason. 

Where do we use the indices which can overflow? The indices are used only on [line 60-61](https://github.com/graphcore-research/pyscf-ipu/blob/4aac401fc0cefdcff58f3c47a97a2a610737cefd/nanoDFT/compute_indices.cpp#L60C39-L60C39) one of which gets used (a bit scary) on line 23 where we compute [sqrt(1+8*value)](https://github.com/graphcore-research/pyscf-ipu/blob/4aac401fc0cefdcff58f3c47a97a2a610737cefd/nanoDFT/compute_indices.cpp#L23). 

A few ideas 
1. The indices appear to be sorted by size, so we can keep a uint64 counter for the position at which it overflows. 
2. We can do the line 62 operation in uint64 (and the sqrt on line 23 in double). 
3. Perhaps we can find another formula. 

(if the uint64 counter works, we might use more uint64 counters and store all indices in uint16 and halve the memory consumption of indices; feels a bit like compressing the indices utilizing the knowledge that they're sorted).

**Comment by awf** [comment]
Currently the "uint64" would compress (i,j,k,l) to one integer, maybe it's worth seeing if we can instead use the mapping (i,j) -> int32, (k,l) -> int32.

**Comment by awf** [comment]
Or use (i16,i16,i16,i16)
