### ISSUE TITLE
Add CPU test cases to continuous integration

### ISSUE THREAD

**Issue by AlexanderMath** [graphcore-research/pyscf-ipu#77]
Trying to install only CPU mode fails due to 

1. `chex` is only installed in `requirements_ipu.txt`. Installing for CPU thus casts `import chex; not found`
3. `direct.py` sets the number of tiles using `NUM_TILES = jax.devices("ipu")[0].num_tiles` which fails in CPU mode. 

We should add the CPU installation to CLI backend so these type of things doesn't block potential CPU users.

**Comment by hatemhelal** [comment]
We should support different ways of installing `pyscf-ipu` e.g. for ourselves we will probably want to do:

```
pip install -e ".[ipu,test]"
```
but could also support a `cpu` argument to the package setup.

**Comment by AlexanderMath** [comment]
No need, current readme says default installation is CPU. We should just make sure that works. 

```
To run this package on a standard CPU machine (laptop or server), install the base Python requirements:

pip install -r requirements.txt
```

**Comment by hatemhelal** [comment]
I think we should lean on the standard feature for managing optional dependencies:

https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

We can sort out the readme to match this too.
